### Obtener todos los usuarios
GET http://localhost:1234/users

### Seleccionar un usuario
GET http://localhost:1234/users/11ee51cb-241c-2268-aeea-b48c9daeb3a7

### Agregar un usuario
POST http://localhost:1234/users
Content-Type: application/json

{
    "FullName": "Carlos Alberto Delgado Galeano",
    "Email": "carlos.delgado.galeano@correounivalle.edu.co",
    "Username": "petus.delgado",
    "Password": "petus123",
    "Phone": "0000000000",
    "Role": "Student"
}

### Actualizar un usuario
PATCH http://localhost:1234/users/cf8e0ccd-51da-11ee-aeea-b48c9daeb3a7
Content-Type: application/json

{
    "FullName": "Carlos Alberto Delgado Galeano",
    "Email": "carlos.delgado.galeano@correounivalle.edu.co",
    "Username": "petus.delgado",
    "Password": "petus123",
    "Phone": "3183764127",
    "Role": "Student"
}

### Eliminar un usuario
DELETE http://localhost:1234/users/aeec6beb-51da-11ee-aeea-b48c9daeb3a7