### Get programs
GET http://localhost:1234/programs

### Get a program
GET http://localhost:1234/programs/1

### Create a program
POST http://localhost:1234/programs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6IjViMTlmNTg4LTYwMTUtMTFlZS05OGJkLWI0OGM5ZGFlYjNhNyIsIkZ1bGxOYW1lIjoiQ2FybG9zIEFsYmVydG8gRGVsZ2FkbyBHYWxlYW5vIiwiRW1haWwiOiJjYXJsb3MuZGVsZ2Fkby5nYWxlYW5vQGNvcnJlb3VuaXZhbGxlLmVkdS5jbyIsIlBhc3N3b3JkIjoiJDJiJDEyJEFWU2tnUXg5VUc2ek5JRjNNNzFwcGV5b3RqU2VlN0FOQU4wRHIwYWFWSDBDakpVUkFHRzVlIiwiUGhvbmUiOiIxMjM0NTY3ODkwIiwiUm9sZSI6IlN0dWRlbnQiLCJpYXQiOjE2OTYxNjQzMTF9.OQqIlKB6fB2vJvcB8f7HEom6BMsxIcoIM20G0OkvdZM

{
    "ID": 1234,
    "ProgramName": "Nutrición y Dietética"
}

### Update a program
PUT http://localhost:1234/programs/1
Content-Type: application/json

{
    "ProgramName": "Ingeniería en alimentos"
}

### Delete a program
DELETE http://localhost:1234/programs/1