### Get all requests
GET http://localhost:1234/requests

### Get a request
GET http://localhost:1234/requests/1

### Create a request
POST http://localhost:1234/requests
Content-Type: application/json

{
    "StartTime": "2023-09-18 08:00:00",
    "EndTime": "2023-09-18 12:00:00",
    "ClassroomID": 1,
    "ActivityDescription": "Fundamentos de Gestión Tecnológica",
    "UserID": "27165b47-55d6-11ee-baad-b48c9daeb3a7",
    "ProgramID": 3743
}

### TODO: fix the date issue.