### Obtener todos los usuarios
GET http://localhost:1234/users

### Seleccionar un usuario
GET http://localhost:1234/users/11ee51cb-241c-2268-aeea-b48c9daeb3a7

### Agregar un usuario
POST http://localhost:1234/users
Content-Type: application/json

{
    "FullName": "Jesus Alberto Gil Ayala",
    "Email": "jesus.gil@correounivalle.edu.co",
    "Password": "pirlo420",
    "Phone": 1234567890,
    "Role": "Student"
}

### Actualizar un usuario
PUT http://localhost:1234/users/b89044e0-55ce-11ee-baad-b48c9daeb3a7
Content-Type: application/json

{
    "FullName": "Juan Sebastian Gonzalez Camacho",
    "Email": "juan.s.gonzalez.c@correounivalle.edu.co",
    "Password": "juan123",
    "Phone": 3175852505,
    "Role": "Student"
}

### Eliminar un usuario
DELETE http://localhost:1234/users/f369ee26-6070-11ee-884d-b48c9daeb3a7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6IjViMTlmNTg4LTYwMTUtMTFlZS05OGJkLWI0OGM5ZGFlYjNhNyIsIkZ1bGxOYW1lIjoiQ2FybG9zIEFsYmVydG8gRGVsZ2FkbyBHYWxlYW5vIiwiRW1haWwiOiJjYXJsb3MuZGVsZ2Fkby5nYWxlYW5vQGNvcnJlb3VuaXZhbGxlLmVkdS5jbyIsIlBhc3N3b3JkIjoiJDJiJDEyJEFWU2tnUXg5VUc2ek5JRjNNNzFwcGV5b3RqU2VlN0FOQU4wRHIwYWFWSDBDakpVUkFHRzVlIiwiUGhvbmUiOiIxMjM0NTY3ODkwIiwiUm9sZSI6IlN0dWRlbnQiLCJpYXQiOjE2OTYxNjQzMTF9.OQqIlKB6fB2vJvcB8f7HEom6BMsxIcoIM20G0OkvdZM